Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 

Var
   num, tabuada, multiplica :inteiro
   
Inicio
      escreval("Digite uma tabuada: ")
      leia(tabuada)
      
      num <- 1
      enquanto num <= 10 faca

               multiplica <- tabuada*num
               escreval(tabuada," x",num," =",multiplica)
               num <- num+1
      fimenquanto


Fimalgoritmo